// ─── Per-location fetch tables ─────────────────────────────────────────────
//
// Auto-generated by scripts/generate_fetch_tables.py from shoreline_data.json.
// Stepping ray-cast at 15 m intervals with point-in-polygon water test.
// Review values near narrows before committing — connector polygons are
// approximate and may yield larger-than-expected south/north fetches.
//
const FETCH_TABLES: Record<string, FetchEntry[]> = {

  // 5152 Lake Grove Road — 45.30325°N, 85.01259°W
  // East shore of West Arm, ~0.83 mi N of WA narrows
  'lake-grove-road': [
    { bearing:   0.00, mi: 0.05 }, // N
    { bearing:  11.25, mi: 0.05 }, // NbE
    { bearing:  22.50, mi: 0.05 }, // NNE
    { bearing:  33.75, mi: 0.05 }, // NEbN
    { bearing:  45.00, mi: 0.05 }, // NE
    { bearing:  56.25, mi: 0.05 }, // NEbE
    { bearing:  67.50, mi: 0.05 }, // ENE
    { bearing:  78.75, mi: 0.05 }, // EbN
    { bearing:  90.00, mi: 0.05 }, // E
    { bearing: 101.25, mi: 0.05 }, // EbS
    { bearing: 112.50, mi: 0.05 }, // ESE
    { bearing: 123.75, mi: 0.05 }, // SEbE
    { bearing: 135.00, mi: 0.05 }, // SE
    { bearing: 146.25, mi: 0.05 }, // SEbS
    { bearing: 157.50, mi: 0.40 }, // SSE
    { bearing: 168.75, mi: 0.55 }, // SbE
    { bearing: 180.00, mi: 0.75 }, // S
    { bearing: 191.25, mi: 0.85 }, // SbW
    { bearing: 202.50, mi: 1.25 }, // SSW
    { bearing: 213.75, mi: 0.70 }, // SWbS
    { bearing: 225.00, mi: 0.65 }, // SW
    { bearing: 236.25, mi: 0.65 }, // SWbW
    { bearing: 247.50, mi: 0.70 }, // WSW
    { bearing: 258.75, mi: 0.90 }, // WbS
    { bearing: 270.00, mi: 0.85 }, // W
    { bearing: 281.25, mi: 0.85 }, // WbN
    { bearing: 292.50, mi: 0.90 }, // WNW
    { bearing: 303.75, mi: 1.40 }, // NWbW
    { bearing: 315.00, mi: 2.10 }, // NW
    { bearing: 326.25, mi: 2.65 }, // NWbN
    { bearing: 337.50, mi: 0.05 }, // NNW
    { bearing: 348.75, mi: 0.05 }, // NbW
  ],

  // Bear Cove Marina — 45.32611°N, 85.04358°W
  // 3052 Hilton Ln, west shore of West Arm, ~0.7 mi S of Mud Lake narrows
  'bear-cove-marina': [
    { bearing:   0.00, mi: 0.65 }, // N
    { bearing:  11.25, mi: 0.55 }, // NbE
    { bearing:  22.50, mi: 0.50 }, // NNE
    { bearing:  33.75, mi: 0.45 }, // NEbN
    { bearing:  45.00, mi: 0.50 }, // NE
    { bearing:  56.25, mi: 0.55 }, // NEbE
    { bearing:  67.50, mi: 0.50 }, // ENE
    { bearing:  78.75, mi: 0.45 }, // EbN
    { bearing:  90.00, mi: 0.50 }, // E
    { bearing: 101.25, mi: 0.55 }, // EbS
    { bearing: 112.50, mi: 0.70 }, // ESE
    { bearing: 123.75, mi: 1.35 }, // SEbE
    { bearing: 135.00, mi: 2.05 }, // SE
    { bearing: 146.25, mi: 2.75 }, // SEbS
    { bearing: 157.50, mi: 0.85 }, // SSE
    { bearing: 168.75, mi: 0.05 }, // SbE
    { bearing: 180.00, mi: 0.05 }, // S
    { bearing: 191.25, mi: 0.05 }, // SbW
    { bearing: 202.50, mi: 0.05 }, // SSW
    { bearing: 213.75, mi: 0.05 }, // SWbS
    { bearing: 225.00, mi: 0.05 }, // SW
    { bearing: 236.25, mi: 0.05 }, // SWbW
    { bearing: 247.50, mi: 0.05 }, // WSW
    { bearing: 258.75, mi: 0.05 }, // WbS
    { bearing: 270.00, mi: 0.05 }, // W
    { bearing: 281.25, mi: 0.05 }, // WbN
    { bearing: 292.50, mi: 0.05 }, // WNW
    { bearing: 303.75, mi: 0.05 }, // NWbW
    { bearing: 315.00, mi: 0.05 }, // NW
    { bearing: 326.25, mi: 0.05 }, // NWbN
    { bearing: 337.50, mi: 0.05 }, // NNW
    { bearing: 348.75, mi: 0.05 }, // NbW
  ],

  // Walloon Village — 45.26352°N, 84.93499°W
  // SE tip of The Foot; Bear Creek drainage outlet is nearby
  'legacy-water-sports': [
    { bearing:   0.00, mi: 0.05 }, // N
    { bearing:  11.25, mi: 0.10 }, // NbE
    { bearing:  22.50, mi: 0.10 }, // NNE
    { bearing:  33.75, mi: 0.10 }, // NEbN
    { bearing:  45.00, mi: 0.05 }, // NE
    { bearing:  56.25, mi: 0.05 }, // NEbE
    { bearing:  67.50, mi: 0.05 }, // ENE
    { bearing:  78.75, mi: 0.05 }, // EbN
    { bearing:  90.00, mi: 0.05 }, // E
    { bearing: 101.25, mi: 0.05 }, // EbS
    { bearing: 112.50, mi: 0.05 }, // ESE
    { bearing: 123.75, mi: 0.05 }, // SEbE
    { bearing: 135.00, mi: 0.10 }, // SE
    { bearing: 146.25, mi: 0.10 }, // SEbS
    { bearing: 157.50, mi: 0.15 }, // SSE
    { bearing: 168.75, mi: 0.15 }, // SbE
    { bearing: 180.00, mi: 0.20 }, // S
    { bearing: 191.25, mi: 0.25 }, // SbW
    { bearing: 202.50, mi: 0.30 }, // SSW
    { bearing: 213.75, mi: 0.30 }, // SWbS
    { bearing: 225.00, mi: 0.75 }, // SW
    { bearing: 236.25, mi: 0.85 }, // SWbW
    { bearing: 247.50, mi: 0.95 }, // WSW
    { bearing: 258.75, mi: 1.85 }, // WbS
    { bearing: 270.00, mi: 1.95 }, // W
    { bearing: 281.25, mi: 4.10 }, // WbN
    { bearing: 292.50, mi: 2.00 }, // WNW
    { bearing: 303.75, mi: 0.45 }, // NWbW
    { bearing: 315.00, mi: 0.30 }, // NW
    { bearing: 326.25, mi: 0.25 }, // NWbN
    { bearing: 337.50, mi: 0.15 }, // NNW
    { bearing: 348.75, mi: 0.15 }, // NbW
  ],

  // Jones Landing (N. Arm) — 45.30219°N, 84.96792°W
  // 5186 Jones Landing, east shore of North Arm, mid-arm
  'jones-landing': [
    { bearing:   0.00, mi: 0.40 }, // N
    { bearing:  11.25, mi: 0.40 }, // NbE
    { bearing:  22.50, mi: 0.05 }, // NNE
    { bearing:  33.75, mi: 0.05 }, // NEbN
    { bearing:  45.00, mi: 0.05 }, // NE
    { bearing:  56.25, mi: 0.05 }, // NEbE
    { bearing:  67.50, mi: 0.05 }, // ENE
    { bearing:  78.75, mi: 0.05 }, // EbN
    { bearing:  90.00, mi: 0.05 }, // E
    { bearing: 101.25, mi: 0.05 }, // EbS
    { bearing: 112.50, mi: 0.05 }, // ESE
    { bearing: 123.75, mi: 0.05 }, // SEbE
    { bearing: 135.00, mi: 0.05 }, // SE
    { bearing: 146.25, mi: 0.15 }, // SEbS
    { bearing: 157.50, mi: 0.15 }, // SSE
    { bearing: 168.75, mi: 1.25 }, // SbE
    { bearing: 180.00, mi: 3.40 }, // S
    { bearing: 191.25, mi: 0.70 }, // SbW
    { bearing: 202.50, mi: 0.65 }, // SSW
    { bearing: 213.75, mi: 0.60 }, // SWbS
    { bearing: 225.00, mi: 0.55 }, // SW
    { bearing: 236.25, mi: 0.45 }, // SWbW
    { bearing: 247.50, mi: 0.40 }, // WSW
    { bearing: 258.75, mi: 0.50 }, // WbS
    { bearing: 270.00, mi: 0.55 }, // W
    { bearing: 281.25, mi: 0.60 }, // WbN
    { bearing: 292.50, mi: 0.60 }, // WNW
    { bearing: 303.75, mi: 0.60 }, // NWbW
    { bearing: 315.00, mi: 0.50 }, // NW
    { bearing: 326.25, mi: 0.45 }, // NWbN
    { bearing: 337.50, mi: 0.45 }, // NNW
    { bearing: 348.75, mi: 0.45 }, // NbW
  ],

};

// Backward-compat alias — old ID used in existing DynamoDB records / client code
(FETCH_TABLES as Record<string, FetchEntry[]>)['legacy-water-sports'] = FETCH_TABLES['walloon-village']!;

(FETCH_TABLES as Record<string, FetchEntry[]>)['walloon-village'] = FETCH_TABLES['legacy-water-sports']!;