#!/usr/bin/env python3
"""
generate_fetch_tables.py

Reads scripts/shoreline_data.json, assembles the lake polygon boundary,
then ray-casts from each preset location at the 32 compass bearings used
by waveCalc.ts.

Approach: step outward from each preset in the bearing direction at 15 m
intervals; use point-in-polygon (ray-casting) against all lake polygons to
determine when the ray exits the lake.  This correctly respects "only travel
over water" — rays through land that would otherwise reach another basin are
blocked at the shore.

Writes a ready-to-paste FETCH_TABLES TypeScript block to
scripts/fetch_tables_generated.ts and prints it to stdout.

To update waveCalc.ts:
    python3 scripts/generate_fetch_tables.py
    # review scripts/fetch_tables_generated.ts, then paste into waveCalc.ts
"""

import json
import math
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
DATA_PATH = REPO_ROOT / "scripts" / "shoreline_data.json"
OUT_PATH  = REPO_ROOT / "scripts" / "fetch_tables_generated.ts"

with open(DATA_PATH) as f:
    data = json.load(f)

# ── Projection ────────────────────────────────────────────────────────────────
REF_LAT    = 45.29
M_PER_DEG  = 111_320.0
COS_LAT    = math.cos(math.radians(REF_LAT))
MI_PER_M   = 1.0 / 1609.34

def to_xy(lat: float, lng: float) -> tuple[float, float]:
    return lng * COS_LAT * M_PER_DEG, lat * M_PER_DEG

# ── Polygon assembly ──────────────────────────────────────────────────────────

def resolve_ref(ref: str) -> list[dict]:
    node: object = data
    for key in ref.split("."):
        node = node[key]  # type: ignore[index]
    if isinstance(node, list):
        return [p for p in node if "lat" in p and "lng" in p]
    if isinstance(node, dict) and "lat" in node:
        return [node]
    return []

def build_poly_edges(poly_def: dict) -> list[tuple[tuple[float,float], tuple[float,float]]]:
    pts: list[tuple[float, float]] = []
    for seg in poly_def["segments"]:
        if "ref" in seg:
            items = resolve_ref(seg["ref"])
            if seg.get("reverse"):
                items = list(reversed(items))
        else:
            items = [p for p in seg["points"] if "lat" in p and "lng" in p]
        pts.extend(to_xy(p["lat"], p["lng"]) for p in items)
    n = len(pts)
    return [(pts[i], pts[(i + 1) % n]) for i in range(n) if pts[i] != pts[(i + 1) % n]]

# One edge-list per polygon — used for per-polygon point-in-polygon tests.
polygon_edge_lists: list[list] = [
    build_poly_edges(p) for p in data["polygons"]
]

# ── Point-in-polygon (ray-casting, horizontal ray eastward) ──────────────────

def pip(px: float, py: float, edges: list) -> bool:
    count = 0
    for (x1, y1), (x2, y2) in edges:
        if min(y1, y2) <= py < max(y1, y2):
            xi = x1 + (py - y1) / (y2 - y1) * (x2 - x1)
            if xi > px:
                count += 1
    return count % 2 == 1

def in_lake(px: float, py: float) -> bool:
    return any(pip(px, py, edges) for edges in polygon_edge_lists)

# ── Stepping ray-cast ─────────────────────────────────────────────────────────
# Step outward 15 m at a time.  Return distance to first land contact,
# rounded to nearest 0.05 mi, minimum 0.05.

STEP_M  = 15.0
MAX_M   = 9_000.0    # ~5.6 mi — longest possible fetch on Walloon Lake

def ray_fetch_mi(lat: float, lng: float, bearing_deg: float) -> float:
    ox, oy = to_xy(lat, lng)
    brad   = math.radians(bearing_deg)
    dx     = math.sin(brad)
    dy     = math.cos(brad)

    prev_t = 0.0
    steps  = int(MAX_M / STEP_M)
    for i in range(1, steps + 1):
        t  = i * STEP_M
        px = ox + t * dx
        py = oy + t * dy
        if not in_lake(px, py):
            # midpoint between last in-water step and first out-of-water step
            mid = (prev_t + t) * 0.5
            return max(0.05, round(mid * MI_PER_M * 20) / 20)
        prev_t = t

    return round(MAX_M * MI_PER_M * 20) / 20

# ── 32-point compass rose ─────────────────────────────────────────────────────

BEARINGS = [i * 11.25 for i in range(32)]
COMPASS  = [
    "N",    "NbE",  "NNE",  "NEbN", "NE",   "NEbE", "ENE",  "EbN",
    "E",    "EbS",  "ESE",  "SEbE", "SE",   "SEbS", "SSE",  "SbE",
    "S",    "SbW",  "SSW",  "SWbS", "SW",   "SWbW", "WSW",  "WbS",
    "W",    "WbN",  "WNW",  "NWbW", "NW",   "NWbN", "NNW",  "NbW",
]

# ── Generate TypeScript output ────────────────────────────────────────────────

print("Computing fetch tables (stepping ray-cast)…", flush=True)

lines: list[str] = [
    "// ─── Per-location fetch tables ─────────────────────────────────────────────",
    "//",
    "// Auto-generated by scripts/generate_fetch_tables.py from shoreline_data.json.",
    "// Stepping ray-cast at 15 m intervals with point-in-polygon water test.",
    "// Review values near narrows before committing — connector polygons are",
    "// approximate and may yield larger-than-expected south/north fetches.",
    "//",
    "const FETCH_TABLES: Record<string, FetchEntry[]> = {",
]

for preset in data["presets"]:
    pid   = preset["id"]
    lat   = preset["lat"]
    lng   = preset["lng"]
    name  = preset["name"]
    notes = preset.get("notes", "")

    print(f"  {pid}…", flush=True)
    lines.append("")
    lines.append(f"  // {name} — {lat}°N, {abs(lng):.5f}°W")
    if notes:
        lines.append(f"  // {notes}")
    lines.append(f"  '{pid}': [")
    for b, label in zip(BEARINGS, COMPASS):
        mi = ray_fetch_mi(lat, lng, b)
        lines.append(f"    {{ bearing: {b:6.2f}, mi: {mi:.2f} }}, // {label}")
    lines.append("  ],")

# Alias: walloon-village = legacy-water-sports
lines.append("")
lines.append("};")
lines.append("")
lines.append(
    "// Backward-compat alias — old ID used in existing DynamoDB records / client code"
)
lines.append(
    "(FETCH_TABLES as Record<string, FetchEntry[]>)"
    "['legacy-water-sports'] = FETCH_TABLES['walloon-village']!;"
)
lines.append("")
lines.append(
    "(FETCH_TABLES as Record<string, FetchEntry[]>)"
    "['walloon-village'] = FETCH_TABLES['legacy-water-sports']!;"
)

output = "\n".join(lines)
OUT_PATH.write_text(output)
print("\n" + output)
print(f"\n✓ Written to {OUT_PATH}", flush=True)
